version: '3'

networks:

  lm_network:
    driver: bridge


volumes:

  dbdata:


services:

  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - ./mariadb:/bitnami/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password
    ports:
      - 3307:3306

  app:
    image: 'php:7.3-apache'
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
    ports:
      - 81:80
    volumes:
      - ./src:/var/www/html
